version: '3'
services:
  django:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    # Log printing via Rich is enhanced by a TTY
    tty: true
    env_file: ./dev/.env.docker-compose
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - .:/opt/django-project
      - ${SAMPLES_DIR-./samples}:${SAMPLES_DIR-/srv/samples}
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - rabbitmq
      - minio

  celery:
    build:
      context: .
      dockerfile: ./dev/django.Dockerfile
    command: [
      "celery",
      "--app", "miqa.celery",
      "worker",
      "--loglevel", "INFO",
      "--without-heartbeat"
    ]
    # Docker Compose does not set the TTY width, which causes Celery errors
    tty: false
    env_file: ./dev/.env.docker-compose
    volumes:
      - .:/opt/django-project
      - ${SAMPLES_DIR-./samples}:${SAMPLES_DIR-/srv/samples}
    depends_on:
      - postgres
      - rabbitmq
      - minio

  npm:
    image: node:latest
    command: ["npm", "run", "serve"]
    working_dir: /opt/client
    volumes:
      - ./client:/opt/client
    ports:
      - 8081:8081
