site_name: MIQA
site_description: Documentation for MIQA
site_author: Kitware

repo_url: https://github.com/OpenImaging/miqa

theme:
  name: material
  logo: images/kitware-mark.png
  highlightjs: true
  palette:
    primary: black
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

extra_css: [extra.css]

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/OpenImaging/miqa

nav:
  - User Guide:
    - Home: index.md
    - Navigating the site: site.md
    - Users in MIQA: users.md
    - Projects in MIQA: projects.md
  - Administrator Guide:
    - Introduction: admin.md
    - Setting up MIQA: setup.md
    - The Django Admin Console: console.md
    - Imports and Exports: imports.md
    - Integrating MIQA in your workflow: integration.md
