name: Cache tox
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: "3.8"
    # - name: cache-tox
    #   id: cache-tox
    #   uses: actions/cache@v3
    #   env:
    #     cache-name: cache-tox
    #   with:
    #     path: ./.tox/
    #     key: ${{ runner.os }}-tox-${{ hashFiles('**/requirements*.txt') }}
    #     restore-keys: ${{ runner.os }}-tox-
    - name: install-tox
      shell: bash
      run: |
          pip install --upgrade pip &&
          pip install tox
