name: Cache lfs
runs:
  using: composite
  steps:
    - name: cache-lfs
      id: cache-lfs
      uses: actions/cache@v3
      env:
        cache-name: cache-lfs
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('**/*.pth') }}
        restore-keys: ${{ runner.os }}-lfs-
    - name: fetch-lfs
      if: inputs.fetch-lfs == 'true'
      continue-on-error: true
      shell: bash
      run: git lfs fetch && git lfs pull
