version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: django
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
    ports:
      - ${DOCKER_POSTGRES_PORT-5432}

  django:
    build:
      context: ..
      dockerfile: ./prod/django.Dockerfile
      args:
        # Pass configuration variables to the build process so manage.py can be used
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
        DJANGO_CONFIGURATION: ${DJANGO_CONFIGURATION}
        DJANGO_DATABASE_URL: ${DJANGO_DATABASE_URL}
        DJANGO_DEFAULT_FROM_EMAIL: ${DJANGO_DEFAULT_FROM_EMAIL}
        DJANGO_EMAIL_URL: ${DJANGO_EMAIL_URL}
        DJANGO_MIQA_URL_PREFIX: ${DJANGO_MIQA_URL_PREFIX}
        DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
        VUE_APP_OAUTH_API_ROOT: ${VUE_APP_OAUTH_API_ROOT}

    # TODO install and use a wsgi server
    command: ["./manage.py", "runserver", "0.0.0.0:8000"]
    # Log printing via Rich is enhanced by a TTY
    tty: true
    env_file: ./.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - "${MIQA_MOUNT_DIR}:${MIQA_MOUNT_DIR}"
      - "/home/anne/miqa/samples:/mnt/mydata"
      - "/home/anne/miqa/samples:/srv/samples"
    ports:
      - ${MIQA_SERVER_PORT}:8000
    depends_on:
      - postgres
