# Generated by Django 3.2 on 2021-05-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_default_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='decision',
            field=models.CharField(choices=[('NONE', '-'), ('GOOD', 'Good'), ('BAD', 'Bad'), ('USABLE_EXTRA', 'Usable extra')], default='NONE', max_length=20),
        ),
    ]
