# Generated by Django 3.2.3 on 2021-05-28 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_image_paths_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='decision',
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                (
                    'decision',
                    models.CharField(
                        choices=[
                            ('NONE', '-'),
                            ('GOOD', 'Good'),
                            ('BAD', 'Bad'),
                            ('USABLE_EXTRA', 'Usable extra'),
                        ],
                        default='NONE',
                        max_length=20,
                    ),
                ),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    'scan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='annotations',
                        to='core.scan',
                    ),
                ),
            ],
        ),
    ]
