# Generated by Django 3.2 on 2021-05-10 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_scan_decision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='session',
        ),
    ]
