# Generated by Django 3.2.3 on 2021-06-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0004_auto_20210601_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotation',
            options={'ordering': ['-created']},
        ),
        migrations.AddIndex(
            model_name='annotation',
            index=models.Index(fields=['scan', '-created'], name='core_annota_scan_id_75f12a_idx'),
        ),
    ]
