# Generated by Django 3.2 on 2021-07-07 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0006_auto_20210609_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannote',
            name='initials',
            field=models.CharField(default='??', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scannote',
            name='creator',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
