# Generated by Django 3.2.5 on 2021-08-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210812_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
