# Generated by Django 3.2.7 on 2021-09-17 12:35

from django.db import migrations, models

import miqa.core.models.session


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_experiment_lock_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='evaluation_models',
            field=models.JSONField(
                default=miqa.core.models.session.default_evaluation_model_mapping
            ),
        ),
        migrations.AlterField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(
                choices=[
                    ('ncanda-t1spgr-v1', 'ncanda-t1spgr-v1'),
                    ('ncanda-mprage-v1', 'ncanda-mprage-v1'),
                ],
                max_length=255,
            ),
        ),
    ]
