# Generated by Django 3.2 on 2021-09-21 16:38

import uuid

from django.conf import settings
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor
from django.db.migrations.state import StateApps
import django.db.models.deletion
import django_extensions.db.fields

import miqa.core.models.project


def migrate_sessions_to_projects(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    Session = apps.get_model('core', 'Session')  # noqa: N806
    Project = apps.get_model('core', 'Project')  # noqa: N806
    Experiment = apps.get_model('core', 'Experiment')  # noqa: N806

    # Copy all Sessions into Projects
    projects = []
    for session in Session.objects.all():
        project = Project(
            created=session.created,
            modified=session.modified,
            id=session.id,
            name=session.name,
            creator=session.creator,
            archived=session.archived,
            import_path=session.import_path,
            export_path=session.export_path,
            evaluation_models=session.evaluation_models,
        )
        projects.append(project)
    Project.objects.bulk_create(projects)

    # Update all Experiments to point to the correct Project
    experiments = []
    for experiment in Experiment.objects.all():
        experiment.project = Project.objects.get(id=experiment.session.id)
        experiments.append(experiment)
    Experiment.objects.bulk_update(experiments, ['project'])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0013_evaluations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                (
                    'created',
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name='created'
                    ),
                ),
                (
                    'modified',
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name='modified'
                    ),
                ),
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                (
                    'creator',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        # Temporarily allow null values until the data can be copied over
                        null=True,
                    ),
                ),
                ('archived', models.BooleanField(default=False)),
                ('import_path', models.CharField(max_length=500)),
                ('export_path', models.CharField(max_length=500)),
                (
                    'evaluation_models',
                    models.JSONField(
                        default=miqa.core.models.project.default_evaluation_model_mapping
                    ),
                ),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='experiments',
                to='core.project',
                # Temporarily allow null values until experiment.project has been copied over
                null=True,
                default=None,
            ),
            preserve_default=False,
        ),
        # Migrate all Sessions to Projects, and link all Experiments to the corresponding Project
        migrations.RunPython(migrate_sessions_to_projects),
        # Remove the temporary null option from the Experiment.project field
        migrations.AlterField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='experiments',
                to='core.project',
            ),
            preserve_default=False,
        ),
        # Remove the temporary null option from Project.creator
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.RemoveConstraint(
            model_name='experiment',
            name='experiment_session_name_unique',
        ),
        migrations.RemoveIndex(
            model_name='experiment',
            name='core_experi_session_be49ba_idx',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='session',
        ),
        migrations.AddIndex(
            model_name='experiment',
            index=models.Index(fields=['project', 'name'], name='core_experi_project_ecad46_idx'),
        ),
        migrations.AddConstraint(
            model_name='experiment',
            constraint=models.UniqueConstraint(
                fields=('project', 'name'), name='experiment_project_name_unique'
            ),
        ),
        migrations.RemoveField(
            model_name='session',
            name='creator',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
