# Generated by Django 3.2.8 on 2021-10-29 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_scan_decision'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
