# Generated by Django 3.2.8 on 2021-11-05 19:29
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0017_remove_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluation',
            name='image',
        ),
        migrations.RenameModel('Image', 'Frame'),
        migrations.AddField(
            model_name='evaluation',
            name='frame',
            field=models.ForeignKey(
                default=None, on_delete=django.db.models.deletion.PROTECT, to='core.frame'
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='frame',
            index=models.Index(
                fields=['scan', 'frame_number'], name='core_frame_scan_id_ea9adc_idx'
            ),
        ),
        migrations.RemoveIndex(
            model_name='frame',
            name='core_image_scan_id_26e3ff_idx',
        ),
        migrations.AlterField(
            model_name='frame',
            name='scan',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='core.scan'
            ),
        ),
    ]
