# Generated by Django 3.2.9 on 2021-11-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_unique_evaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={
                'permissions': (
                    ('collaborators', 'Collaborators'),
                    ('tier_1_reviewers', 'Tier 1 Reviewers'),
                    ('tier_2_reviewers', 'Tier 2 Reviewers'),
                )
            },
        ),
    ]
