# Generated by Django 3.2.9 on 2021-11-11 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_unique_evaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('collaborator', 'Collaborator'), ('tier_1_reviewer', 'Tier 1 Reviewer'), ('tier_2_reviewer', 'Tier 2 Reviewer'))},
        ),
    ]
