# Generated by Django 3.2.9 on 2021-11-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_unique_evaluation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('submit_reviews', 'Submit Reviews'),)},
        ),
    ]
