# Generated by Django 3.2.9 on 2021-11-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scandecision',
            name='decision',
            field=models.CharField(choices=[('U', 'Usable'), ('UE', 'Usable-Extra'), ('Q?', 'Questionable'), ('UN', 'Unusable')], max_length=2),
        ),
    ]
