# Generated by Django 3.2.9 on 2021-11-30 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_update_qc_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='global_import_export',
            field=models.BooleanField(default=False),
        ),
    ]
