# Generated by Django 3.2.10 on 2022-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_user_identified_artifacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='scandecision',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
