# Generated by Django 3.2.10 on 2022-02-08 22:13

from django.db import migrations, models


def migrate_global_project(apps: StateApps, schema_editor: BaseDatabaseSchemaEditor):
    Project = apps.get_model('core', 'Project')  # noqa: N806
    GlobalSettings = apps.get_model('core', 'GlobalSettings')  # noqa: N806

    if global_project := Project.objects.filter(global_import_export=True).first():
        gs = GlobalSettings.load()
        gs.import_path = global_project.import_path
        gs.export_path = global_project.export_path
        gs.save()
        global_project.delete()


class Migration(migrations.Migration):

    replaces = [
        ('core', '0025_decision_location'),
        ('core', '0026_merge_0025_decision_location_0025_globalsettings'),
        ('core', '0027_remove_project_global_boolean'),
    ]

    dependencies = [
        ('core', '0024_alter_frame_raw_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scandecision',
            name='location',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='project',
            name='global_import_export',
        ),
    ]
