# Generated by Django 3.2.10 on 2022-02-08 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ('core', '0025_decision_location'),
        ('core', '0026_merge_0025_decision_location_0025_globalsettings'),
        ('core', '0027_remove_project_global_boolean'),
    ]

    dependencies = [
        ('core', '0024_alter_frame_raw_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scandecision',
            name='location',
            field=models.JSONField(default=dict),
        ),
        migrations.RemoveField(
            model_name='project',
            name='global_import_export',
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('import_path', models.CharField(blank=True, default='', max_length=1000)),
                ('export_path', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
