# Generated by Django 3.2.10 on 2022-02-02 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_frame_raw_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='scandecision',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
