# Generated by Django 3.2.10 on 2022-02-10 19:38

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_globals_and_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='content',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
