# Generated by Django 3.2.10 on 2022-02-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_decision_location'),
        ('core', '0025_globalsettings'),
    ]

    operations = []
