# Generated by Django 3.2.10 on 2022-02-04 22:00

from django.db import migrations
import s3_file_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_0025_decision_location_0025_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='frame',
            name='content',
            field=s3_file_field.fields.S3FileField(null=True),
        ),
    ]
