# Generated by Django 3.2.10 on 2022-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0027_experiment_lock_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='export_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='import_path',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
