# Generated by Django 3.2.10 on 2022-03-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_project_settings_optional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='default_email_recipients',
            field=models.TextField(blank=True),
        ),
    ]
