# Generated by Django 3.2.13 on 2022-04-14 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_optional_scan_fields'),
        ('core', '0030_project_s3_public'),
    ]

    operations = []
