# Generated by Django 3.2.12 on 2022-04-22 17:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0030_scan_subject_session'),
        ('core', '0031_merge_20220414_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='session_ID',
        ),
        migrations.RemoveField(
            model_name='scan',
            name='subject_ID',
        ),
    ]
