# Generated by Django 3.2.13 on 2022-05-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20220422_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='neurology_orientation',
            field=models.BooleanField(
                default=True,
                help_text='If true, scans will be rendered with LPS orientation, else with RAS orientation',
            ),
        ),
    ]
