# Generated by Django 3.2.13 on 2022-05-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20220422_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='anatomy_orientation',
            field=models.CharField(
                choices=[('LPS', 'LPS'), ('RAS', 'RAS')], default='LPS', max_length=3
            ),
        ),
    ]
