# Generated by Django 3.2.15 on 2022-09-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20220912_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='artifact_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.settingsgroup'),
        ),
    ]
