name: cache
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cache-lfs:
    runs-on: ubuntu-latest

    - name: Cache git lfs
      uses: actions/cache@v3
      env:
          cache-name: cache-lfs
      with:
        path: .git/lfs
        key: ${{ hashFiles('miqa/learning/models/*.pth') }}

      - run: git lfs fetch && git lfs pull
        if: steps.cache-lfs.outputs.cache-hit != 'true'


  cache-pip:
    runs-on: ubuntu-latest

    steps:
      - name: Cache pip dependencies
      - uses: actions/cache@v3
        env:
          cache-name: cache-venv
        with:
          path: ./.venv/
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-
      - run: python -m venv ./.venv && . ./.venv/bin/activate &&
            pip install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'

  cache-node-modules:
    runs-on: ubuntu-latest

    steps:
      - name: Cache node modules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: npm install
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
