name: ci
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
      minio:
        # This image does not require any command arguments (which GitHub Actions don't support)
        # TODO at the time this was pinned, latest bitnami/minio was broken
        image: bitnami/minio:2022.2.18
        env:
          MINIO_ACCESS_KEY: minioAccesskey
          MINIO_SECRET_KEY: minioSecretkey
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Run tests
        run: |
          tox
        env:
          DJANGO_CONFIGURATION: DevelopmentConfiguration
          DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
          DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
          DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccesskey
          DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretkey
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
  test-pyppeteer:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
      minio:
        # This image does not require any command arguments (which GitHub Actions don't support)
        # TODO at the time this was pinned, latest bitnami/minio was broken
        image: bitnami/minio:2022.2.18
        env:
          MINIO_ACCESS_KEY: minioAccessKey
          MINIO_SECRET_KEY: minioSecretKey
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Run tests
        uses: docker://ghcr.io/girder/pytest-pyppeteer:v0.0.9
        with:
          install_directory: client
          install_command: npm install
          test_directory: .
          test_command: tox -e test-pyppeteer
        env:
          DJANGO_DATABASE_URL: postgres://postgres:postgres@postgres:5432/django
          DJANGO_MINIO_STORAGE_ENDPOINT: minio:9000
          DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
          DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
          DJANGO_STORAGE_BUCKET_NAME: integration-test-bucket
  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run lint -- --no-fix
      - run: npm run build
