name: ci
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tox
      - uses: ./.github/actions/npm
      - run: tox -e lint
      - run: cd client && npm run lint -- --no-fix

  pytests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
      minio:
        # TODO at the time this was pinned, latest bitnami/minio was broken
        image: bitnami/minio:2022.2.18
        env:
          MINIO_ROOT_USER: minioAccessKey
          MINIO_ROOT_PASSWORD: minioSecretKey
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/lfs
      - uses: ./.github/actions/tox
      - run: tox
        env:
          DJANGO_CONFIGURATION: DevelopmentConfiguration
          DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
          DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
          DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
          DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
          DJANGO_STORAGE_BUCKET_NAME: django-storage
      - uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true

  pyppeteer:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
      minio:
        image: bitnami/minio:latest
        env:
          MINIO_ROOT_USER: minioAccessKey
          MINIO_ROOT_PASSWORD: minioSecretKey
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/tox
      - uses: ./.github/actions/lfs
      - uses: ./.github/actions/npm
      - uses: docker://ghcr.io/girder/pytest-pyppeteer:v0.0.11
        with:
          install_directory: client
          install_command: npm install
          test_directory: .
          test_command: tox -e test-pyppeteer
        env:
          DJANGO_DATABASE_URL: postgres://postgres:postgres@postgres:5432/django
          DJANGO_MINIO_STORAGE_ENDPOINT: minio:9000
          DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
          DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
          DJANGO_STORAGE_BUCKET_NAME: integration-test-bucket
