name: ci
on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/tox
      - uses: ./.github/actions/npm
      - run: tox -e lint
      - run: cd web_client && npm run lint -- --no-fix

  pytests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
      minio:
        # TODO at the time this was pinned, latest bitnami/minio was broken
        image: bitnami/minio:2022.2.18
        env:
          MINIO_ROOT_USER: minioAccessKey
          MINIO_ROOT_PASSWORD: minioSecretKey
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/lfs
      - uses: ./.github/actions/tox
      - run: tox
        env:
          DJANGO_CONFIGURATION: DevelopmentConfiguration
          DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
          DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
          DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
          DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
          DJANGO_STORAGE_BUCKET_NAME: django-storage

#  playwright:
#    timeout-minutes: 60
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v3
#    - uses: actions/setup-node@v3
#      with:
#        node-version: 16
#    - name: Install dependencies
#      run: cd web_client && npm ci
#    - name: Install Playwright Browsers
#      run: cd web_client && npx playwright install --with-deps
#    - name: Run Playwright tests
#      run: cd web_client && npx playwright test
#    - uses: actions/upload-artifact@v3
#      with:
#        name: playwright-report
#        path: playwright-report/
#        retention-days: 30
